const MAGIC_NUMBERS = {
  HOURS_PER_DAY: 24,
  MINUTES_PER_HOUR: 60,
  SECONDS_PER_MINUTE: 60,
  MILLISECONDS_PER_SECOND: 1000,
  RESEND_INTERVAL_SECONDS: 30,
  NINETEENTH_CENTURY: 1900,
};

export default MAGIC_NUMBERS;
